### ISSUE TITLE
[Question] Status always shows "idle" when AC is on. Is it normal?

### ISSUE THREAD

**Issue by bluefangs** [sman591/homebridge-lg-thinq-ac#71]
LG Air Conditioner Model
MS-Q12SWDZ

Homekit Model number
RAC_056905_WW

When the AC is on, on the status (in the main screen top / room screen top), you will notice the temperature, with "idle". What determines this state? Shouldn't it state "heating" or "cooling" ?

![Screenshot from 2021-04-19 21-42-25](https://user-images.githubusercontent.com/19926675/115268709-2d0db880-a158-11eb-9403-545f178b5058.png)

**Comment by sman591** [comment]
Huh, I haven't seen that before. I'll look into it

**Comment by sman591** [comment]
Ah, this is because HomeKit supports the "current" state and we currently only support the "target" state.

I can "fake" this, but unfortunately LG's API doesn't expose the actual cooling/heating/idle state of your device, so it'll say "cooling" whenever "cool" is set or "heating" whenever "heat" is set, but won't actually indicate what the device is actively doing.

**Comment by bluefangs** [comment]
> I can "fake" this, but unfortunately LG's API doesn't expose the actual cooling/heating/idle state of your device, so it'll say "cooling" whenever "cool" is set or "heating" whenever "heat" is set, but won't actually indicate what the device is actively doing.

I think this should do. Maybe you can set it to "idle" when the ac is "off". Technically it's "on" in the sense that it's connecto to pwoer but just not actively heating or cooling. ¯\_(ツ)_/¯

**Comment by sman591** [comment]
Cool- i added this in the latest plugin version, so it should work now!
