### ISSUE TITLE
Ac is switched off but keeps showing its on in Home app.

### ISSUE THREAD

**Issue by kietiub** [sman591/homebridge-lg-thinq-ac#88]
**LG Air Conditioner Model**
Model #: LW1019IVSM, model in accesories: WIN_056905_WW

"refresh_interval": 1

**Describe the bug**
The AC after being turned off keeps showing up as switched on itself. The AC stays off but the accesory keeps showing as switched on and cooling 

**Symptom check**
* **Does your unit appear in the Home app?** Yes
* **Is the current on/off state, temperature, and mode being reported?** No, its tricky when turned on it shows ok but after turning off the HOME app starts showing it on even when its turned off
* **Does your unit respond to the controls?** Yes

**Relevant logs**

**Comment by sman591** [comment]
This is by design of how the Home app works. A device will remain in your app unless it is removed by the bridge (in this case, Homebridge)

If you wish to remove your A/C unit, you can do so by:
1. Turn the unit off
2. Wait 5 minutes + verify the device is "offline" in the LG app
3. Checking this box in the config UI (see below)
4. Restart homebridge

<img width="399" alt="Screen Shot 2022-02-02 at 11 14 43 PM" src="https://user-images.githubusercontent.com/1441807/152297819-c871d0e8-aaa7-411a-a4d7-98812bd2883a.png">
